// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnyfbmamgcqswyuqafpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndueWZibWFtZ2Nxc3d5dXFhZnBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MjU5MzIsImV4cCI6MjA1NTIwMTkzMn0.tID8tTCpC9G3fG4jR1m1eUiunLi0g65xecnsum7sUks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);